(function(){
    var modules={
        "panel-main":    			{url:"$H/m/panel-main.html",router:1},
        "panel-child":    			{url:"$H/m/panel-child.html"},
        "panel-export-part1":       {url:"$H/m/panel-export-part1.html",router:1},
        "panel-export-screening":   {url:"$H/m/panel-export-screened.html",router:1},
        "panel-export-v1-enrolled":    {url:"$H/m/panel-export-v1-enrolled.html",router:1},
        "panel-export-v2-enrolled":    {url:"$H/m/panel-export-v2-enrolled.html",router:1},
        "panel-export-bl-enrolled":    {url:"$H/m/panel-export-bl-enrolled.html",router:1},
        "export-data-hush": {url:"$H/m/export-data.html",Table:"hush-export",form_module:"export-form-hush"},
        "export-form-hush": {url:"$H/m/export-form.html",Table:"hush-export"},
        
        "participant-data":   		{url:"$H/m/participant/participant-data.html",Table:"hush-participant",form_module:"participant-form",router:1,
                                            child_panel1:"panel-child1",
                                            child_panel2:"panel-child2",
                                            questionnaire_setup:"online-questionnaire-setup-hush",
                                            online_questionnaire:"online-questionnaire-app-hush"
                                        },
        "participant-active-data":   		{url:"$H/m/participant/participant-data.html",Table:"hush-participant",form_module:"participant-form",router:1,
                                        child_panel1:"panel-child1",
                                        child_panel2:"panel-child2",
                                        questionnaire_setup:"online-questionnaire-setup-hush",
                                        online_questionnaire:"online-questionnaire-app-hush",
                                        participant_id:{field1:"Subject_ID",field2:"Subject_Initials"},
                                        query_a:{I2:{"$lt":2}} 
                                    },
                                    
        "participant-form":   		{url:"$H/m/participant/participant-form.html",Table:"hush-participant"},

        "online-questionnaire-setup-hush": 	{url:"$H/m/oq-setup.html",Table:"hush-participant"},
        "online-questionnaire-app-hush":    {url:"$H/oq.html"},

        "notes-data":  	                    {url:"$H/m/library/notes-data.html",Table:"hush-notes",form_module:"notes-form",router:1},
        "notes-form":  	                    {url:"$H/m/library/notes-form.html",Table:"hush-notes"},

        "hush-randomisation-table-data":		    {url:"$H/m/library/randomisation-table-data.html",Table:"hush-randomisation-table",form_module:"hush-randomisation-table-form"},
        "hush-randomisation-table-form":		    {url:"$H/m/library/randomisation-table-form.html",Table:"hush-randomisation-table"},
        "hush-randomisation-upload-data":		    {url:"$H/m/library/randomisation-upload-data.html",Table:"hush-randomisation-upload",form_module:"hush-randomisation-upload-form",task_name:"Randomisation Document"},
        "hush-randomisation-upload-form":		    {url:"$H/m/library/randomisation-upload-form.html",Table:"hush-randomisation-upload",task_name:"Randomisation Document"},
        "hush-concom-medication-data":            {url:"$H/m/library/concom-medication-data.html",Table:"hush-concom-medication",form_module:"hush-concom-medication-form",task_name:"Concom Medication"},
        "hush-concom-medication-form":            {url:"$H/m/library/concom-medication-form.html",Table:"hush-concom-medication"},
        "hush-adverse-event-data":                {url:"$H/m/library/adverse-event-data.html",Table:"hush-adverse-event",form_module:"hush-adverse-event-form",task_name:"Adverse Event"},
        "hush-adverse-event-form":                {url:"$H/m/library/adverse-event-form.html",Table:"hush-adverse-event"},

        "hush-pis-data":		            {url:"$H/m/library/pis-data.html",Table:"hush-pis",form_module:"hush-pis-form",task_name:"Participant Information Sheet"},
        "hush-pis-form":		            {url:"$H/m/library/pis-form.html",Table:"hush-pis",task_name:"Participant Information Sheet"},
        "hush-consent-data":		            {url:"$H/m/library/consent-data.html",Table:"hush-consent",form_module:"hush-p1-consent-form",task_name:"Consent Form"},
        "hush-pconsent-form":		            {url:"$H/m/library/consent-form.html",Table:"hush-consent",task_name:"Consent Form"},
        "hush-s-demographic-data":		            {url:"$H/m/library/demographic-data.html",Table:"hush-s-demographic",form_module:"hush-s-demographic-form",task_name:"Screening demographic"},
        "hush-s-demographic-form":		            {url:"$H/m/library/demographic-form.html",Table:"hush-s-demographic",task_name:"Screening - demographic"},
        "hush-s-isi-data":		            {url:"$H/m/library/isi-data.html",Table:"hush-s-isi",form_module:"hush-s-isi-form",task_name:"Screening - ISI"},
        "hush-s-isi-form":		            {url:"$H/m/library/isi-form.html",Table:"hush-s-isi",task_name:"Screening - ISI"},
        "hush-s-stop-bang-data":		            {url:"$H/m/library/stop-bang-data.html",Table:"hush-s-stop-bang",form_module:"hush-s-stop-bang-form",task_name:"Screening - STOP-BANG"},
        "hush-s-stop-bang-form":		            {url:"$H/m/library/stop-bang-form.html",Table:"hush-s-stop-bang",task_name:"Screening - STOP-BANG"},
        "hush-s-health-profile-data":		            {url:"$H/m/library/health-profile-s-data.html",Table:"hush-s-health-profile",form_module:"hush-s-health-profile-form",task_name:"Screening - Health Profile"},
        "hush-s-health-profile-form":		            {url:"$H/m/library/health-profile-s-form.html",Table:"hush-s-health-profile",task_name:"Screening - Health Profile"},
        "hush-s-caffeine-data":		            {url:"$H/m/library/caffeine-data.html",Table:"hush-s-caffeine",form_module:"hush-s-caffeine-form",task_name:"Screening - Caffeine intake"},
        "hush-s-caffeine-form":		            {url:"$H/m/library/caffeine-form.html",Table:"hush-s-caffeine",task_name:"Screening - Caffeine intake"},
        "hush-s-alcohol-data":		            {url:"$H/m/library/alcohol-data.html",Table:"hush-s-alcohol",form_module:"hush-s-alcohol-form",task_name:"Screening - Alcohol Screen"},
        "hush-s-alcohol-form":		            {url:"$H/m/library/alcohol-form.html",Table:"hush-s-alcohol",task_name:"Screening - Alcohol Screen"},

        "hush-bl-isi-data":		            {url:"$H/m/library/isi-data.html",Table:"hush-bl-isi",form_module:"hush-bl-isi-form",task_name:"Baseline - ISI"},
        "hush-bl-isi-form":		            {url:"$H/m/library/isi-form.html",Table:"hush-bl-isi",task_name:"Baseline - ISI"},
        "hush-bl-psqi-data":		            {url:"$H/m/library/psqi-data.html",Table:"hush-bl-psqi",form_module:"hush-bl-psqi-form",task_name:"Baseline - Pittsburgh Sleep Quality Index (PSQI)"},
        "hush-bl-psqi-form":		            {url:"$H/m/library/psqi-form.html",Table:"hush-bl-psqi",task_name:"Baseline - Pittsburgh Sleep Quality Index (PSQI)"},
        "hush-bl-ess-data":		            {url:"$H/m/library/ess-data.html",Table:"hush-bl-ess",form_module:"hush-bl-ess-form",task_name:"Baseline - Epworth Sleepiness Scale"},
        "hush-bl-ess-form":		            {url:"$H/m/library/ess-form.html",Table:"hush-bl-ess",task_name:"Baseline - Epworth Sleepiness Scale"},
        "hush-bl-nprs-data":		            {url:"$H/m/library/nprs-data.html",Table:"hush-bl-nprs",form_module:"hush-bl-nprs-form",task_name:"Baseline - The Numeric Pain Rating Scale"},
        "hush-bl-nprs-form":		            {url:"$H/m/library/nprs-form.html",Table:"hush-bl-nprs",task_name:"Baseline - The Numeric Pain Rating Scale"},
        "hush-bl-dass-data":		            {url:"$H/m/library/dass-data.html",Table:"hush-bl-dass",form_module:"hush-bl-dass-form",task_name:"Baseline - Depression, Anxiety and Stress Scales (DASS-21)"},
        "hush-bl-dass-form":		            {url:"$H/m/library/dass-form.html",Table:"hush-bl-dass",task_name:"Baseline - Depression, Anxiety and Stress Scales (DASS-21)"},
        "hush-bl-whoqol-brev-data":		            {url:"$H/m/library/whoqol-brev-data.html",Table:"hush-bl-whoqol-brev",form_module:"hush-bl-whoqol-brev-form",task_name:"Baseline - WHOQOL-BREF"},
        "hush-bl-whoqol-brev-form":		            {url:"$H/m/library/whoqol-brev-form.html",Table:"hush-bl-whoqol-brev",task_name:"Baseline - WHOQOL-BREF"},
        "hush-bl-health-profile-data":		            {url:"$H/m/library/health-profile-s-data.html",Table:"hush-bl-health-profile",form_module:"hush-bl-health-profile-form",task_name:"Baseline - Health Profile"},
        "hush-bl-health-profile-form":		            {url:"$H/m/library/health-profile-s-form.html",Table:"hush-bl-health-profile",task_name:"Baseline - Health Profile"},
        "hush-bl-caffeine-data":		            {url:"$H/m/library/caffeine-data.html",Table:"hush-bl-caffeine",form_module:"hush-bl-caffeine-form",task_name:"Baseline - Caffeine intake"},
        "hush-bl-caffeine-form":		            {url:"$H/m/library/caffeine-form.html",Table:"hush-bl-caffeine",task_name:"Baseline - Caffeine intake"},
        "hush-bl-alcohol-data":		            {url:"$H/m/library/alcohol-data.html",Table:"hush-bl-alcohol",form_module:"hush-bl-alcohol-form",task_name:"Baseline - Alcohol Screen"},
        "hush-bl-alcohol-form":		            {url:"$H/m/library/alcohol-form.html",Table:"hush-bl-alcohol",task_name:"Baseline - Alcohol Screen"},
        "hush-bl-driving-data":		            {url:"$H/m/library/driving-data.html",Table:"hush-bl-driving",form_module:"hush-bl-driving-form",task_name:"Baseline - Driving questions"},
        "hush-bl-driving-form":		            {url:"$H/m/library/driving-form.html",Table:"hush-bl-driving",task_name:"Baseline - Driving questions"},
        "hush-bl-physical-activity-data":		            {url:"$H/m/library/physical-activity-data.html",Table:"hush-bl-physical-activity",form_module:"hush-bl-physical-activity-form",task_name:"Baseline - Physical Activity and Sports Performance"},
        "hush-bl-physical-activity-form":		            {url:"$H/m/library/physical-activity-form.html",Table:"hush-bl-physical-activity",task_name:"Baseline - Physical Activity and Sports Performance"},
        "hush-bl-minor-illnesses-data":		            {url:"$H/m/library/minor-illnesses-data.html",Table:"hush-bl-minor-illnesses",form_module:"hush-bl-minor-illnesses-form",task_name:"Baseline - Susceptibility to Minor illnesses"},
        "hush-bl-minor-illnesses-form":		            {url:"$H/m/library/minor-illnesses-form.html",Table:"hush-bl-isi",task_name:"Baseline - Susceptibility to Minor illnesses"},

        "hush-w2-isi-data":		            {url:"$H/m/library/isi-data.html",Table:"hush-w2-isi",form_module:"hush-w2-isi-form",task_name:"Week 2 - ISI"},
        "hush-w2-isi-form":		            {url:"$H/m/library/isi-form.html",Table:"hush-w2-isi",task_name:"Week 2 - ISI"},
        "hush-w2-psqi-data":		            {url:"$H/m/library/psqi-data.html",Table:"hush-w2-psqi",form_module:"hush-w2-psqi-form",task_name:"Week 2 - Pittsburgh Sleep Quality Index (PSQI)"},
        "hush-w2-psqi-form":		            {url:"$H/m/library/psqi-form.html",Table:"hush-w2-psqi",task_name:"Week 2 - Pittsburgh Sleep Quality Index (PSQI)"},
        "hush-w2-ess-data":		            {url:"$H/m/library/ess-data.html",Table:"hush-w2-ess",form_module:"hush-w2-ess-form",task_name:"Week 2 - Epworth Sleepiness Scale"},
        "hush-w2-ess-form":		            {url:"$H/m/library/ess-form.html",Table:"hush-w2-ess",task_name:"Week 2 - Epworth Sleepiness Scale"},
        "hush-w2-nprs-data":		            {url:"$H/m/library/nprs-data.html",Table:"hush-w2-nprs",form_module:"hush-w2-nprs-form",task_name:"Week 2 - The Numeric Pain Rating Scale"},
        "hush-w2-nprs-form":		            {url:"$H/m/library/nprs-form.html",Table:"hush-w2-nprs",task_name:"Week 2 - The Numeric Pain Rating Scale"},
        "hush-w2-dass-data":		            {url:"$H/m/library/dass-data.html",Table:"hush-w2-dass",form_module:"hush-w2-dass-form",task_name:"Week 2 - Depression, Anxiety and Stress Scales (DASS-21)"},
        "hush-w2-dass-form":		            {url:"$H/m/library/dass-form.html",Table:"hush-w2-dass",task_name:"Week 2 - Depression, Anxiety and Stress Scales (DASS-21)"},
        "hush-w2-whoqol-brev-data":		            {url:"$H/m/library/whoqol-brev-data.html",Table:"hush-w2-whoqol-brev",form_module:"hush-w2-whoqol-brev-form",task_name:"Week 2 - WHOQOL-BREF"},
        "hush-w2-whoqol-brev-form":		            {url:"$H/m/library/whoqol-brev-form.html",Table:"hush-w2-whoqol-brev",task_name:"Week 2 - WHOQOL-BREF"},
        "hush-w2-health-profile-data":		            {url:"$H/m/library/health-profile-data.html",Table:"hush-w2-health-profile",form_module:"hush-w2-health-profile-form",task_name:"Week 2 - Health Profile"},
        "hush-w2-health-profile-form":		            {url:"$H/m/library/health-profile-form.html",Table:"hush-w2-health-profile",task_name:"Week 2 - Health Profile"},
        "hush-w2-caffeine-data":		            {url:"$H/m/library/caffeine-data.html",Table:"hush-w2-caffeine",form_module:"hush-w2-caffeine-form",task_name:"Week 2 - Caffeine intake"},
        "hush-w2-caffeine-form":		            {url:"$H/m/library/caffeine-form.html",Table:"hush-w2-caffeine",task_name:"Week 2 - Caffeine intake"},
        "hush-w2-alcohol-data":		            {url:"$H/m/library/alcohol-data.html",Table:"hush-w2-alcohol",form_module:"hush-w2-alcohol-form",task_name:"Week 2 - Alcohol Screen"},
        "hush-w2-alcohol-form":		            {url:"$H/m/library/alcohol-form.html",Table:"hush-w2-alcohol",task_name:"Week 2 - Alcohol Screen"},
        "hush-w2-driving-data":		            {url:"$H/m/library/driving-data.html",Table:"hush-w2-driving",form_module:"hush-w2-driving-form",task_name:"Week 2 - Driving questions"},
        "hush-w2-driving-form":		            {url:"$H/m/library/driving-form.html",Table:"hush-w2-driving",task_name:"Week 2 - Driving questions"},
        "hush-w2-physical-activity-data":		            {url:"$H/m/library/physical-activity-data.html",Table:"hush-w2-physical-activity",form_module:"hush-w2-physical-activity-form",task_name:"Week 2 - Physical Activity and Sports Performance"},
        "hush-w2-physical-activity-form":		            {url:"$H/m/library/physical-activity-form.html",Table:"hush-w2-physical-activity",task_name:"Week 2 - Physical Activity and Sports Performance"},
        "hush-w2-minor-illnesses-data":		            {url:"$H/m/library/minor-illnesses-data.html",Table:"hush-w2-minor-illnesses",form_module:"hush-w2-minor-illnesses-form",task_name:"Week 2 - Susceptibility to Minor illnesses"},
        "hush-w2-minor-illnesses-form":		            {url:"$H/m/library/minor-illnesses-form.html",Table:"hush-w2-minor-illnesses",task_name:"Week 2 - Susceptibility to Minor illnesses"},
        "hush-w2-adverse-effects-data":		            {url:"$H/m/library/adverse-effects-data.html",Table:"hush-w2-adverse-effects",form_module:"hush-w2-adverse-effects-form",task_name:"Week 2 - Adverse Effects"},
        "hush-w2-adverse-effects-form":		            {url:"$H/m/library/adverse-effects-form.html",Table:"hush-w2-adverse-effects",task_name:"Week 2 - Adverse Effects"},

        "hush-w4-isi-data":		            {url:"$H/m/library/isi-data.html",Table:"hush-w4-isi",form_module:"hush-w4-isi-form",task_name:"Week 4 - ISI"},
        "hush-w4-isi-form":		            {url:"$H/m/library/isi-form.html",Table:"hush-w4-isi",task_name:"Week 4 - ISI"},
        "hush-w4-psqi-data":		            {url:"$H/m/library/psqi-data.html",Table:"hush-w4-psqi",form_module:"hush-w4-psqi-form",task_name:"Week 4 - Pittsburgh Sleep Quality Index (PSQI)"},
        "hush-w4-psqi-form":		            {url:"$H/m/library/psqi-form.html",Table:"hush-w4-psqi",task_name:"Week 4 - Pittsburgh Sleep Quality Index (PSQI)"},
        "hush-w4-ess-data":		            {url:"$H/m/library/ess-data.html",Table:"hush-w4-ess",form_module:"hush-w4-ess-form",task_name:"Week 4 - Epworth Sleepiness Scale"},
        "hush-w4-ess-form":		            {url:"$H/m/library/ess-form.html",Table:"hush-w4-ess",task_name:"Week 4 - Epworth Sleepiness Scale"},
        "hush-w4-nprs-data":		            {url:"$H/m/library/nprs-data.html",Table:"hush-w4-nprs",form_module:"hush-w4-nprs-form",task_name:"Week 4 - The Numeric Pain Rating Scale"},
        "hush-w4-nprs-form":		            {url:"$H/m/library/nprs-form.html",Table:"hush-w4-nprs",task_name:"Week 4 - The Numeric Pain Rating Scale"},
        "hush-w4-dass-data":		            {url:"$H/m/library/dass-data.html",Table:"hush-w4-dass",form_module:"hush-w4-dass-form",task_name:"Week 4 - Depression, Anxiety and Stress Scales (DASS-21)"},
        "hush-w4-dass-form":		            {url:"$H/m/library/dass-form.html",Table:"hush-w4-dass",task_name:"Week 4 - Depression, Anxiety and Stress Scales (DASS-21)"},
        "hush-w4-whoqol-brev-data":		            {url:"$H/m/library/whoqol-brev-data.html",Table:"hush-w4-whoqol-brev",form_module:"hush-w4-whoqol-brev-form",task_name:"Week 4 - WHOQOL-BREF"},
        "hush-w4-whoqol-brev-form":		            {url:"$H/m/library/whoqol-brev-form.html",Table:"hush-w4-whoqol-brev",task_name:"Week 4 - WHOQOL-BREF"},
        "hush-w4-health-profile-data":		            {url:"$H/m/library/health-profile-data.html",Table:"hush-w4-health-profile",form_module:"hush-w4-health-profile-form",task_name:"Week 4 - Health Profile"},
        "hush-w4-health-profile-form":		            {url:"$H/m/library/health-profile-form.html",Table:"hush-w4-health-profile",task_name:"Week 4 - Health Profile"},
        "hush-w4-caffeine-data":		            {url:"$H/m/library/caffeine-data.html",Table:"hush-w4-caffeine",form_module:"hush-w4-caffeine-form",task_name:"Week 4 - Caffeine intake"},
        "hush-w4-caffeine-form":		            {url:"$H/m/library/caffeine-form.html",Table:"hush-w4-caffeine",task_name:"Week 4 - Caffeine intake"},
        "hush-w4-alcohol-data":		            {url:"$H/m/library/alcohol-data.html",Table:"hush-w4-alcohol",form_module:"hush-w4-alcohol-form",task_name:"Week 4 - Alcohol Screen"},
        "hush-w4-alcohol-form":		            {url:"$H/m/library/alcohol-form.html",Table:"hush-w4-alcohol",task_name:"Week 4 - Alcohol Screen"},
        "hush-w4-driving-data":		            {url:"$H/m/library/driving-data.html",Table:"hush-w4-driving",form_module:"hush-w4-driving-form",task_name:"Week 4 - Driving questions"},
        "hush-w4-driving-form":		            {url:"$H/m/library/driving-form.html",Table:"hush-w4-driving",task_name:"Week 4 - Driving questions"},
        "hush-w4-physical-activity-data":		            {url:"$H/m/library/physical-activity-data.html",Table:"hush-w4-physical-activity",form_module:"hush-w4-physical-activity-form",task_name:"Week 4 - Physical Activity and Sports Performance"},
        "hush-w4-physical-activity-form":		            {url:"$H/m/library/physical-activity-form.html",Table:"hush-w4-physical-activity",task_name:"Week 4 - Physical Activity and Sports Performance"},
        "hush-w4-minor-illnesses-data":		            {url:"$H/m/library/minor-illnesses-data.html",Table:"hush-w4-minor-illnesses",form_module:"hush-w4-minor-illnesses-form",task_name:"Week 4 - Susceptibility to Minor illnesses"},
        "hush-w4-minor-illnesses-form":		            {url:"$H/m/library/minor-illnesses-form.html",Table:"hush-w4-minor-illnesses",task_name:"Week 4 - Susceptibility to Minor illnesses"},
        "hush-w4-adverse-effects-data":		            {url:"$H/m/library/adverse-effects-data.html",Table:"hush-w4-adverse-effects",form_module:"hush-w4-adverse-effects-form",task_name:"Week 4 - Adverse Effects"},
        "hush-w4-adverse-effects-form":		            {url:"$H/m/library/adverse-effects-form.html",Table:"hush-w4-adverse-effects",task_name:"Week 4 - Adverse Effects"},
        "hush-w4-sleep-diary-data":		            {url:"$H/m/library/sleep-diary-data.html",Table:"hush-w4-sleep-diary",form_module:"hush-w4-sleep-diary-form",task_name:"Week 4 - Sleep Diary"},
        "hush-w4-sleep-diary-form":		            {url:"$H/m/library/sleep-diary-form.html",Table:"hush-w4-sleep-diary",task_name:"Week 4 - Sleep Diary"},
        "hush-w4-geneactive-data":		            {url:"$H/m/library/geneactive-data.html",Table:"hush-w4-geneactive",form_module:"hush-w4-geneactive-form",task_name:"Week 4 - GENEActive Actigraphy watch"},
        "hush-w4-geneactive-form":		            {url:"$H/m/library/geneactive-form.html",Table:"hush-w4-geneactive",task_name:"Week 4 - GENEActive Actigraphy watch"},

        "hush-w6-isi-data":		            {url:"$H/m/library/isi-data.html",Table:"hush-w6-isi",form_module:"hush-w6-isi-form",task_name:"Week 6 - ISI"},
        "hush-w6-isi-form":		            {url:"$H/m/library/isi-form.html",Table:"hush-w6-isi",task_name:"Week 6 - ISI"},
        "hush-w6-psqi-data":		            {url:"$H/m/library/psqi-data.html",Table:"hush-w6-psqi",form_module:"hush-w6-psqi-form",task_name:"Week 6 - Pittsburgh Sleep Quality Index (PSQI)"},
        "hush-w6-psqi-form":		            {url:"$H/m/library/psqi-form.html",Table:"hush-w6-psqi",task_name:"Week 6 - Pittsburgh Sleep Quality Index (PSQI)"},
        "hush-w6-ess-data":		            {url:"$H/m/library/ess-data.html",Table:"hush-w6-ess",form_module:"hush-w6-ess-form",task_name:"Week 6 - Epworth Sleepiness Scale"},
        "hush-w6-ess-form":		            {url:"$H/m/library/ess-form.html",Table:"hush-w6-ess",task_name:"Week 6 - Epworth Sleepiness Scale"},
        "hush-w6-nprs-data":		            {url:"$H/m/library/nprs-data.html",Table:"hush-w6-nprs",form_module:"hush-w6-nprs-form",task_name:"Week 6 - The Numeric Pain Rating Scale"},
        "hush-w6-nprs-form":		            {url:"$H/m/library/nprs-form.html",Table:"hush-w6-nprs",task_name:"Week 6 - The Numeric Pain Rating Scale"},
        "hush-w6-dass-data":		            {url:"$H/m/library/dass-data.html",Table:"hush-w6-dass",form_module:"hush-w6-dass-form",task_name:"Week 6 - Depression, Anxiety and Stress Scales (DASS-21)"},
        "hush-w6-dass-form":		            {url:"$H/m/library/dass-form.html",Table:"hush-w6-dass",task_name:"Week 6 - Depression, Anxiety and Stress Scales (DASS-21)"},
        "hush-w6-whoqol-brev-data":		            {url:"$H/m/library/whoqol-brev-data.html",Table:"hush-w6-whoqol-brev",form_module:"hush-w6-whoqol-brev-form",task_name:"Week 6 - WHOQOL-BREF"},
        "hush-w6-whoqol-brev-form":		            {url:"$H/m/library/whoqol-brev-form.html",Table:"hush-w6-whoqol-brev",task_name:"Week 6 - WHOQOL-BREF"},
        "hush-w6-health-profile-data":		            {url:"$H/m/library/health-profile-data.html",Table:"hush-w6-health-profile",form_module:"hush-w6-health-profile-form",task_name:"Week 6 - Health Profile"},
        "hush-w6-health-profile-form":		            {url:"$H/m/library/health-profile-form.html",Table:"hush-w6-health-profile",task_name:"Week 6 - Health Profile"},
        "hush-w6-caffeine-data":		            {url:"$H/m/library/caffeine-data.html",Table:"hush-w6-caffeine",form_module:"hush-w6-caffeine-form",task_name:"Week 6 - Caffeine intake"},
        "hush-w6-caffeine-form":		            {url:"$H/m/library/caffeine-form.html",Table:"hush-w6-caffeine",task_name:"Week 6 - Caffeine intake"},
        "hush-w6-alcohol-data":		            {url:"$H/m/library/alcohol-data.html",Table:"hush-w6-alcohol",form_module:"hush-w6-alcohol-form",task_name:"Week 6 - Alcohol Screen"},
        "hush-w6-alcohol-form":		            {url:"$H/m/library/alcohol-form.html",Table:"hush-w6-alcohol",task_name:"Week 6 - Alcohol Screen"},
        "hush-w6-driving-data":		            {url:"$H/m/library/driving-data.html",Table:"hush-w6-driving",form_module:"hush-w6-driving-form",task_name:"Week 6 - Driving questions"},
        "hush-w6-driving-form":		            {url:"$H/m/library/driving-form.html",Table:"hush-w6-driving",task_name:"Week 6 - Driving questions"},
        "hush-w6-physical-activity-data":		            {url:"$H/m/library/physical-activity-data.html",Table:"hush-w6-physical-activity",form_module:"hush-w6-physical-activity-form",task_name:"Week 6 - Physical Activity and Sports Performance"},
        "hush-w6-physical-activity-form":		            {url:"$H/m/library/physical-activity-form.html",Table:"hush-w6-physical-activity",task_name:"Week 6 - Physical Activity and Sports Performance"},
        "hush-w6-minor-illnesses-data":		            {url:"$H/m/library/minor-illnesses-data.html",Table:"hush-w6-minor-illnesses",form_module:"hush-w6-minor-illnesses-form",task_name:"Week 6 - Susceptibility to Minor illnesses"},
        "hush-w6-minor-illnesses-form":		            {url:"$H/m/library/minor-illnesses-form.html",Table:"hush-w6-minor-illnesses",task_name:"Week 6 - Susceptibility to Minor illnesses"},
        "hush-w6-adverse-effects-data":		            {url:"$H/m/library/adverse-effects-data.html",Table:"hush-w6-adverse-effects",form_module:"hush-w6-adverse-effects-form",task_name:"Week 6 - Adverse Effects"},
        "hush-w6-adverse-effects-form":		            {url:"$H/m/library/adverse-effects-form.html",Table:"hush-w6-adverse-effects",task_name:"Week 6 - Adverse Effects"},

        "hush-w8-isi-data":		            {url:"$H/m/library/isi-data.html",Table:"hush-w8-isi",form_module:"hush-w8-isi-form",task_name:"Week 8 - ISI"},
        "hush-w8-isi-form":		            {url:"$H/m/library/isi-form.html",Table:"hush-w8-isi",task_name:"Week 8 - ISI"},
        "hush-w8-psqi-data":		            {url:"$H/m/library/psqi-data.html",Table:"hush-w8-psqi",form_module:"hush-w8-psqi-form",task_name:"Week 8 - Pittsburgh Sleep Quality Index (PSQI)"},
        "hush-w8-psqi-form":		            {url:"$H/m/library/psqi-form.html",Table:"hush-w8-psqi",task_name:"Week 8 - Pittsburgh Sleep Quality Index (PSQI)"},
        "hush-w8-ess-data":		            {url:"$H/m/library/ess-data.html",Table:"hush-w8-ess",form_module:"hush-w8-ess-form",task_name:"Week 8 - Epworth Sleepiness Scale"},
        "hush-w8-ess-form":		            {url:"$H/m/library/ess-form.html",Table:"hush-w8-ess",task_name:"Week 8 - Epworth Sleepiness Scale"},
        "hush-w8-nprs-data":		            {url:"$H/m/library/nprs-data.html",Table:"hush-w8-nprs",form_module:"hush-w8-nprs-form",task_name:"Week 8 - The Numeric Pain Rating Scale"},
        "hush-w8-nprs-form":		            {url:"$H/m/library/nprs-form.html",Table:"hush-w8-nprs",task_name:"Week 8 - The Numeric Pain Rating Scale"},
        "hush-w8-dass-data":		            {url:"$H/m/library/dass-data.html",Table:"hush-w8-dass",form_module:"hush-w8-dass-form",task_name:"Week 8 - Depression, Anxiety and Stress Scales (DASS-21)"},
        "hush-w8-dass-form":		            {url:"$H/m/library/dass-form.html",Table:"hush-w8-dass",task_name:"Week 8 - Depression, Anxiety and Stress Scales (DASS-21)"},
        "hush-w8-whoqol-brev-data":		            {url:"$H/m/library/whoqol-brev-data.html",Table:"hush-w8-whoqol-brev",form_module:"hush-w8-whoqol-brev-form",task_name:"Week 8 - WHOQOL-BREF"},
        "hush-w8-whoqol-brev-form":		            {url:"$H/m/library/whoqol-brev-form.html",Table:"hush-w8-whoqol-brev",task_name:"Week 8 - WHOQOL-BREF"},
        "hush-w8-health-profile-data":		            {url:"$H/m/library/health-profile-data.html",Table:"hush-w8-health-profile",form_module:"hush-w8-health-profile-form",task_name:"Week 8 - Health Profile"},
        "hush-w8-health-profile-form":		            {url:"$H/m/library/health-profile-form.html",Table:"hush-w8-health-profile",task_name:"Week 8 - Health Profile"},
        "hush-w8-caffeine-data":		            {url:"$H/m/library/caffeine-data.html",Table:"hush-w8-caffeine",form_module:"hush-w8-caffeine-form",task_name:"Week 8 - Caffeine intake"},
        "hush-w8-caffeine-form":		            {url:"$H/m/library/caffeine-form.html",Table:"hush-w8-caffeine",task_name:"Week 8 - Caffeine intake"},
        "hush-w8-alcohol-data":		            {url:"$H/m/library/alcohol-data.html",Table:"hush-w8-alcohol",form_module:"hush-w8-alcohol-form",task_name:"Week 8 - Alcohol Screen"},
        "hush-w8-alcohol-form":		            {url:"$H/m/library/alcohol-form.html",Table:"hush-w8-alcohol",task_name:"Week 8 - Alcohol Screen"},
        "hush-w8-driving-data":		            {url:"$H/m/library/driving-data.html",Table:"hush-w8-driving",form_module:"hush-w8-driving-form",task_name:"Week 8 - Driving questions"},
        "hush-w8-driving-form":		            {url:"$H/m/library/driving-form.html",Table:"hush-w8-driving",task_name:"Week 8 - Driving questions"},
        "hush-w8-physical-activity-data":		            {url:"$H/m/library/physical-activity-data.html",Table:"hush-w8-physical-activity",form_module:"hush-w8-physical-activity-form",task_name:"Week 8 - Physical Activity and Sports Performance"},
        "hush-w8-physical-activity-form":		            {url:"$H/m/library/physical-activity-form.html",Table:"hush-w8-physical-activity",task_name:"Week 8 - Physical Activity and Sports Performance"},
        "hush-w8-minor-illnesses-data":		            {url:"$H/m/library/minor-illnesses-data.html",Table:"hush-w8-minor-illnesses",form_module:"hush-w8-minor-illnesses-form",task_name:"Week 8 - Susceptibility to Minor illnesses"},
        "hush-w8-minor-illnesses-form":		            {url:"$H/m/library/minor-illnesses-form.html",Table:"hush-w8-minor-illnesses",task_name:"Week 8 - Susceptibility to Minor illnesses"},
        "hush-w8-adverse-effects-data":		            {url:"$H/m/library/adverse-effects-data.html",Table:"hush-w8-adverse-effects",form_module:"hush-w8-adverse-effects-form",task_name:"Week 8 - Adverse Effects"},
        "hush-w8-adverse-effects-form":		            {url:"$H/m/library/adverse-effects-form.html",Table:"hush-w8-adverse-effects",task_name:"Week 8 - Adverse Effects"},
        "hush-w8-sleep-diary-data":		            {url:"$H/m/library/sleep-diary-data.html",Table:"hush-w8-sleep-diary",form_module:"hush-w8-sleep-diary-form",task_name:"Week 8 - Sleep Diary"},
        "hush-w8-sleep-diary-form":		            {url:"$H/m/library/sleep-diary-form.html",Table:"hush-w8-sleep-diary",task_name:"Week 8 - Sleep Diary"},
        "hush-w8-geneactive-data":		            {url:"$H/m/library/geneactive-data.html",Table:"hush-w8-geneactive",form_module:"hush-w8-geneactive-form",task_name:"Week 8 - GENEActive Actigraphy watch"},
        "hush-w8-geneactive-form":		            {url:"$H/m/library/geneactive-form.html",Table:"hush-w8-geneactive",task_name:"Week 8 - GENEActive Actigraphy watch"},

        "hush-w10-isi-data":		            {url:"$H/m/library/isi-data.html",Table:"hush-w10-isi",form_module:"hush-w10-isi-form",task_name:"Week 10 - ISI"},
        "hush-w10-isi-form":		            {url:"$H/m/library/isi-form.html",Table:"hush-w10-isi",task_name:"Week 10 - ISI"},
        "hush-w10-psqi-data":		            {url:"$H/m/library/psqi-data.html",Table:"hush-w10-psqi",form_module:"hush-w10-psqi-form",task_name:"Week 10 - Pittsburgh Sleep Quality Index (PSQI)"},
        "hush-w10-psqi-form":		            {url:"$H/m/library/psqi-form.html",Table:"hush-w10-psqi",task_name:"Week 10 - Pittsburgh Sleep Quality Index (PSQI)"},
        "hush-w10-ess-data":		            {url:"$H/m/library/ess-data.html",Table:"hush-w10-ess",form_module:"hush-w10-ess-form",task_name:"Week 10 - Epworth Sleepiness Scale"},
        "hush-w10-ess-form":		            {url:"$H/m/library/ess-form.html",Table:"hush-w10-ess",task_name:"Week 10 - Epworth Sleepiness Scale"},
        "hush-w10-nprs-data":		            {url:"$H/m/library/nprs-data.html",Table:"hush-w10-nprs",form_module:"hush-w10-nprs-form",task_name:"Week 10 - The Numeric Pain Rating Scale"},
        "hush-w10-nprs-form":		            {url:"$H/m/library/nprs-form.html",Table:"hush-w10-nprs",task_name:"Week 10 - The Numeric Pain Rating Scale"},
        "hush-w10-dass-data":		            {url:"$H/m/library/dass-data.html",Table:"hush-w10-dass",form_module:"hush-w10-dass-form",task_name:"Week 10 - Depression, Anxiety and Stress Scales (DASS-21)"},
        "hush-w10-dass-form":		            {url:"$H/m/library/dass-form.html",Table:"hush-w10-dass",task_name:"Week 10 - Depression, Anxiety and Stress Scales (DASS-21)"},
        "hush-w10-whoqol-brev-data":		            {url:"$H/m/library/whoqol-brev-data.html",Table:"hush-w10-whoqol-brev",form_module:"hush-w10-whoqol-brev-form",task_name:"Week 10 - WHOQOL-BREF"},
        "hush-w10-whoqol-brev-form":		            {url:"$H/m/library/whoqol-brev-form.html",Table:"hush-w10-whoqol-brev",task_name:"Week 10 - WHOQOL-BREF"},
        "hush-w10-health-profile-data":		            {url:"$H/m/library/health-profile-data.html",Table:"hush-w10-health-profile",form_module:"hush-w10-health-profile-form",task_name:"Week 10 - Health Profile"},
        "hush-w10-health-profile-form":		            {url:"$H/m/library/health-profile-form.html",Table:"hush-w10-health-profile",task_name:"Week 10 - Health Profile"},
        "hush-w10-caffeine-data":		            {url:"$H/m/library/caffeine-data.html",Table:"hush-w10-caffeine",form_module:"hush-w10-caffeine-form",task_name:"Week 10 - Caffeine intake"},
        "hush-w10-caffeine-form":		            {url:"$H/m/library/caffeine-form.html",Table:"hush-w10-caffeine",task_name:"Week 10 - Caffeine intake"},
        "hush-w10-alcohol-data":		            {url:"$H/m/library/alcohol-data.html",Table:"hush-w10-alcohol",form_module:"hush-w10-alcohol-form",task_name:"Week 10 - Alcohol Screen"},
        "hush-w10-alcohol-form":		            {url:"$H/m/library/alcohol-form.html",Table:"hush-w10-alcohol",task_name:"Week 10 - Alcohol Screen"},
        "hush-w10-driving-data":		            {url:"$H/m/library/driving-data.html",Table:"hush-w10-driving",form_module:"hush-w10-driving-form",task_name:"Week 10 - Driving questions"},
        "hush-w10-driving-form":		            {url:"$H/m/library/driving-form.html",Table:"hush-w10-driving",task_name:"Week 10 - Driving questions"},
        "hush-w10-physical-activity-data":		            {url:"$H/m/library/physical-activity-data.html",Table:"hush-w10-physical-activity",form_module:"hush-w10-physical-activity-form",task_name:"Week 10 - Physical Activity and Sports Performance"},
        "hush-w10-physical-activity-form":		            {url:"$H/m/library/physical-activity-form.html",Table:"hush-w10-physical-activity",task_name:"Week 10 - Physical Activity and Sports Performance"},
        "hush-w10-minor-illnesses-data":		            {url:"$H/m/library/minor-illnesses-data.html",Table:"hush-w10-minor-illnesses",form_module:"hush-w10-minor-illnesses-form",task_name:"Week 10 - Susceptibility to Minor illnesses"},
        "hush-w10-minor-illnesses-form":		            {url:"$H/m/library/minor-illnesses-form.html",Table:"hush-w10-minor-illnesses",task_name:"Week 10 - Susceptibility to Minor illnesses"},
        "hush-w10-adverse-effects-data":		            {url:"$H/m/library/adverse-effects-data.html",Table:"hush-w10-adverse-effects",form_module:"hush-w10-adverse-effects-form",task_name:"Week 10 - Adverse Effects"},
        "hush-w10-adverse-effects-form":		            {url:"$H/m/library/adverse-effects-form.html",Table:"hush-w10-adverse-effects",task_name:"Week 10 - Adverse Effects"},

        "hush-e-isi-data":		            {url:"$H/m/library/isi-data.html",Table:"hush-e-isi",form_module:"hush-e-isi-form",task_name:"Exit - ISI"},
        "hush-e-isi-form":		            {url:"$H/m/library/isi-form.html",Table:"hush-e-isi",task_name:"Exit - ISI"},
        "hush-e-psqi-data":		            {url:"$H/m/library/psqi-data.html",Table:"hush-e-psqi",form_module:"hush-e-psqi-form",task_name:"Exit - Pittsburgh Sleep Quality Index (PSQI)"},
        "hush-e-psqi-form":		            {url:"$H/m/library/psqi-form.html",Table:"hush-e-psqi",task_name:"Exit - Pittsburgh Sleep Quality Index (PSQI)"},
        "hush-e-ess-data":		            {url:"$H/m/library/ess-data.html",Table:"hush-e-ess",form_module:"hush-e-ess-form",task_name:"Exit - Epworth Sleepiness Scale"},
        "hush-e-ess-form":		            {url:"$H/m/library/ess-form.html",Table:"hush-e-ess",task_name:"Exit - Epworth Sleepiness Scale"},
        "hush-e-nprs-data":		            {url:"$H/m/library/nprs-data.html",Table:"hush-e-nprs",form_module:"hush-e-nprs-form",task_name:"Exit - The Numeric Pain Rating Scale"},
        "hush-e-nprs-form":		            {url:"$H/m/library/nprs-form.html",Table:"hush-e-nprs",task_name:"Exit - The Numeric Pain Rating Scale"},
        "hush-e-dass-data":		            {url:"$H/m/library/dass-data.html",Table:"hush-e-dass",form_module:"hush-e-dass-form",task_name:"Exit - Depression, Anxiety and Stress Scales (DASS-21)"},
        "hush-e-dass-form":		            {url:"$H/m/library/dass-form.html",Table:"hush-e-dass",task_name:"Exit - Depression, Anxiety and Stress Scales (DASS-21)"},
        "hush-e-whoqol-brev-data":		            {url:"$H/m/library/whoqol-brev-data.html",Table:"hush-e-whoqol-brev",form_module:"hush-e-whoqol-brev-form",task_name:"Exit - WHOQOL-BREF"},
        "hush-e-whoqol-brev-form":		            {url:"$H/m/library/whoqol-brev-form.html",Table:"hush-e-whoqol-brev",task_name:"Exit - WHOQOL-BREF"},
        "hush-e-health-profile-data":		            {url:"$H/m/library/health-profile-data.html",Table:"hush-e-health-profile",form_module:"hush-e-health-profile-form",task_name:"Exit - Health Profile"},
        "hush-e-health-profile-form":		            {url:"$H/m/library/health-profile-form.html",Table:"hush-e-health-profile",task_name:"Exit - Health Profile"},
        "hush-e-caffeine-data":		            {url:"$H/m/library/caffeine-data.html",Table:"hush-e-caffeine",form_module:"hush-e-caffeine-form",task_name:"Exit - Caffeine intake"},
        "hush-e-caffeine-form":		            {url:"$H/m/library/caffeine-form.html",Table:"hush-e-caffeine",task_name:"Exit - Caffeine intake"},
        "hush-e-alcohol-data":		            {url:"$H/m/library/alcohol-data.html",Table:"hush-e-alcohol",form_module:"hush-e-alcohol-form",task_name:"Exit - Alcohol Screen"},
        "hush-e-alcohol-form":		            {url:"$H/m/library/alcohol-form.html",Table:"hush-e-alcohol",task_name:"Exit - Alcohol Screen"},
        "hush-e-driving-data":		            {url:"$H/m/library/driving-data.html",Table:"hush-e-driving",form_module:"hush-e-driving-form",task_name:"Exit - Driving questions"},
        "hush-e-driving-form":		            {url:"$H/m/library/driving-form.html",Table:"hush-e-driving",task_name:"Exit - Driving questions"},
        "hush-e-physical-activity-data":		            {url:"$H/m/library/physical-activity-data.html",Table:"hush-e-physical-activity",form_module:"hush-e-physical-activity-form",task_name:"Exit - Physical Activity and Sports Performance"},
        "hush-e-physical-activity-form":		            {url:"$H/m/library/physical-activity-form.html",Table:"hush-e-physical-activity",task_name:"Exit - Physical Activity and Sports Performance"},
        "hush-e-minor-illnesses-data":		            {url:"$H/m/library/minor-illnesses-data.html",Table:"hush-e-minor-illnesses",form_module:"hush-e-minor-illnesses-form",task_name:"Exit - Susceptibility to Minor illnesses"},
        "hush-e-minor-illnesses-form":		            {url:"$H/m/library/minor-illnesses-form.html",Table:"hush-e-minor-illnesses",task_name:"Exit - Susceptibility to Minor illnesses"},
        "hush-e-adverse-effects-data":		            {url:"$H/m/library/adverse-effects-data.html",Table:"hush-e-adverse-effects",form_module:"hush-e-adverse-effects-form",task_name:"Exit - Adverse Effects"},
        "hush-e-adverse-effects-form":		            {url:"$H/m/library/adverse-effects-form.html",Table:"hush-e-adverse-effects",task_name:"Exit - Adverse Effects"},
        "hush-e-sleep-diary-data":		            {url:"$H/m/library/sleep-diary-data.html",Table:"hush-e-sleep-diary",form_module:"hush-e-sleep-diary-form",task_name:"Exit - Sleep Diary"},
        "hush-e-sleep-diary-form":		            {url:"$H/m/library/sleep-diary-form.html",Table:"hush-e-sleep-diary",task_name:"Exit - Sleep Diary"},
        "hush-e-geneactive-data":		            {url:"$H/m/library/geneactive-data.html",Table:"hush-e-geneactive",form_module:"hush-e-geneactive-form",task_name:"Exit - GENEActive Actigraphy watch"},
        "hush-e-geneactive-form":		            {url:"$H/m/library/geneactive-form.html",Table:"hush-e-geneactive",task_name:"Exit - GENEActive Actigraphy watch"},
    }
    for(p in modules){
        $vm.module_list[p]=modules[p];
        $vm.module_list[p].url=$vm.module_list[p].url.replace('$H',$vm.hosting_path);
    }
    //if(window.location.toString().indexOf('tb=demo')!=-1){
        for(p in $vm.module_list){
            $vm.module_list[p].Table="demo-"+$vm.module_list[p].Table;
        }
    //}

})();
